# BFA-Try-in-PWD

version: '3.7'

services:
      
  nodo-bfa:
    image: bfaar/nodo:test
    ports:
      - 30303:30303
    volumes:
      - /home/bfa
    restart: always


  tsa2-api:
    image: bfaar/tsa2api:test
    ports:
      - 3000:80
    working_dir: /home/bfa/tsa/api
    environment:
      - GETH_HOST=nodo-bfa:8545
      - CONTRACT_ADDRESS_TEST="0xFc0f01A88bD08b988173A2354952087C9492d947"
      - CONTRACT_ABI_PATH="${PWD}/api.json"
      - GETH_ACCOUNT_PASSWORD=
    command: npm run serve
    volumes:
      - /home/bfa      
    restart: always
    depends_on:
      - nodo-bfa 
   
