# BFA-Try-in-PWD

version: '3.7'
services:

#TSA2 API

  tsa2-api:
    image: bfaar/tsa2api:test
    ports:
      - 3000:3000
    working_dir: /home/bfa/tsa/api
    environment:
      - GETH_HOST=nodo-bfa
      - CONTRACT_ADDRESS_TEST="0xFc0f01A88bD08b988173A2354952087C9492d947"
      - CONTRACT_ABI_PATH="/home/bfa/tsa/api/api.json"
      - GETH_ACCOUNT_PASSWORD=
    command: npm run serve
    volumes:
      - /home/bfa      
    restart: always
    networks:
      - testnet
    depends_on:
      - nodo-bfa    
      
#NODO BFA TESTNET

  nodo-bfa:
    image: bfaar/nodo:test
    working_dir: /home/bfa/bfa/bin
    ports:
      - 8545:8545  
    volumes:
      - /home/bfa
    restart: always
    networks:
      - testnet   
      
    
networks:
  testnet: {}
