# BFA-Try-in-PWD

version: '3.7'
services:
#NODO BFA TESTNET
  nodo-bfa:
    image: bfaar/nodo:test
    working_dir: /home/bfa/bfa/bin
    ports:
      - 8545:8545
    expose:
      - 8545
      - 30303      
    volumes:
      - home-bfa:/home/bfa
    restart: always
    networks:
      - testnet
    tsa2-api:
      - backend    
      
#TSA2 API

  tsa2-api:
    image: bfaar/tsa2api:test
    ports:
      - 3000:3000
    working_dir: /home/bfa/tsa/api
    environment:
      - GETH_HOST=http://nodo-bfa:8545
      - CONTRACT_ADDRESS_TEST="0xFc0f01A88bD08b988173A2354952087C9492d947"
      - CONTRACT_ABI_PATH="${PWD}/api.json"
      - GETH_ACCOUNT_PASSWORD=
    command: npm run serve
    volumes:
      - home-bfa:/home/bfa      
    restart: always
    networks:
      - testnet
    depends_on:
      - nodo-bfa    

volumes:
  home-bfa: {}
    
networks:
  testnet: {}
