# BFA-Try-in-PWD

version: '3.1'

services:

  nodo-bfa:
    image: bfaar/nodo:test
    ports:
      - 30303:30303
    volumes:
      - /home/bfa
    restart: always


  tsa2-api:
    image: bfaar/tsa2api:test
    ports:
      - 8546:80
    volumes:
      - /home/bfa      
    restart: always
